server_ip : 128.1.0.1

ssh_exec : /usr/local/openssh/sbin/sshd

config_file : /usr/local/openssh/sshd_config

client_upload_dir : /var/sftp/uploads

srv_upload_dir : /var/sftp

local_data_dir : ~/sftp_files

time_to_live : 60