local_data_dir : /home/ralf/CQT_internship/communication/sftp_test_files/

server_ip : 172.26.56.204

srv_ssh_exec : /usr/local/openssh/sbin/sshd
        
srv_config_file : /usr/local/openssh/sshd_config
        
local_client_upload_dir : /var/sftp/remote_qs_sftp_user_folder/uploads/

local_srv_upload_dir : /var/sftp/

client_ssh_exec : /usr/local/openssh/bin/sftp
        
client_config_file : /usr/local/openssh/ssh_config
        
remote_client_upload_dir : /uploads/
        
remote_srv_upload_dir : /

username : bob_remote
